name: Docker Build and Push

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.server
          push: false
          tags: quay.io/badhikar/sizer:latest

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Push Docker image to Quay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.server
          push: true
          tags: quay.io/badhikar/sizer:latest
