name: Lint, test, and build
on:
  push:
    branches: [main, develop]

jobs:
  build:
    name: basic-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
      - run: npm run test
      - run: GH_TOKEN=${{ secrets.GIST_TOKEN }} npm run build
